---
title: "Bayesian local exchangeability design for phase II basket trials"
author: "Yilin Liu"
date: "10/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("./basket_cluster.R")
source("./basket_part.R")
source("./summary_basket.R")
source("./utils.R")
source("./tuning_bounds.R")
source("./plot_sim_mat.R")
library(grid)
library(gridExtra)
library(cowplot)
library(tidyr)
library(dplyr)
library(clinfun)
library(ggplot2)
```


#### Table 1 Top-10 partitions of the six baskets ($A, \cdots, F$) from Vemurafenib trial

```{r}
x <- c(2, 6, 1, 1, 0, 8)
n <- c(7, 14, 8, 26, 10, 19)
# n <- rep(20, 6)
p0 <- 0.15
R <- length(x)

partitions <- basket_part(x=x, n=n, a0=1, b0=1, max_cl = length(x))

top10_part <- head(partitions, 10)
colnames(top10_part)[1:6] <- paste(LETTERS[1:6], paste(x, n, sep = "/"))
colnames(top10_part)[7] <- "PP"
rownames(top10_part) <- NULL
top10_part
```

```{r}
basket_cluster(partitions, a0=1, b0=1, x=x, n=n)
```


#### Figure 2 Pairwise between basket similarity measure for Vemurafenib trial

```{r}
clusters <- basket_cluster(partitions, a0=1, b0=1, x=x, n=n)
plot_sim_mat(clusters)
```

```{r}
pmat <- rbind(c(0.15, 0.15, 0.15, 0.15, 0.15, 0.15),
              c(0.15, 0.15, 0.15, 0.15, 0.15, 0.45),
              c(0.15, 0.45, 0.15, 0.15, 0.15, 0.45),
              c(0.45, 0.45, 0.15, 0.15, 0.15, 0.45),
              c(0.45, 0.45, 0.45, 0.15, 0.15, 0.45),
              c(0.45, 0.45, 0.45, 0.45, 0.15, 0.45),
              c(0.45, 0.45, 0.45, 0.45, 0.45, 0.45),
              c(0.45, 0.45, 0.15, 0.35, 0.35, 0.45))
```

### MEM local vs. MEM global vs. Exact Binomial

#### Exact Binomial

```{r}
# control FWER by bonferroni correction
ex_binom_fam <- ph2single(0.15, 0.45, 0.0167, 0.2)  # alpha=0.1 / 6
ex_binom_fam

# ph2single(0.15, 0.45, 0.1, 0.12)  # alpha=0.1 / 6
ph2simon(0.15, 0.45, 0.018, 0.2)  # alpha=0.1 / 6
```

```{r}
# Simon's exact probability
r1 <- 1
n1 <- 6
n2 <- 19
r <- 7

# Exact probability of rejecting H0 for Simon's two-stage design
p_rej0 <- sapply(c(0.15, 0.35, 0.45), function(p) {
  1-(pbinom(r1, n1, p) + sum(sapply(c((r1+1):min(n1, r)), function(x) 
  {dbinom(x, n1, p) * pbinom(r-x, n2, p)})))
})

p_rej0

simon_en_mat1 <- n1 + (1 - pbinom(r1, n1, pmat)) * n2

simon_en_mat1
rowSums(simon_en_mat1)
```


```{r}
load("./data/case1_results.RData")

df1 <- data.frame(rbind(tab1[, c(-1, -2, -9)], eq_results[, c(-1, -8)]))
df1$label <- c(rep("MEM-Local", 8), rep("MEM-Global", 8))
df1$label <- factor(df1$label, levels = c("MEM-Local", "MEM-Global"))
df1$sample_size <- rep(19, nrow(df1))
df1$scenario <- c(rep(c(paste(0:6, "Success"), "HHLMMH"), 2))

df1_long_1 <- tidyr::pivot_longer(df1, cols = c(1:6),
                                  names_to = "basket", values_to = "power")
df1_long_1$is_success <- rep(as.numeric(as.vector(t((pmat > 0.15)))), 2)
df1_long_1$is_success <- factor(df1_long_1$is_success, 
                                labels = c("Non-Promising", "Promising"))
df1_long_1 <- df1_long_1 %>% filter(scenario != "HHLMMH")
df1_long_1$n_success <- substr(df1_long_1$scenario, 1, 1)

exact_binom1 <- rbind.data.frame(cbind("Exact-Binomial", 19, paste(c(0:5), "Success"), "X", 0.0163, "Non-Promising", c(0:5)),cbind("Exact-Binomial", 19, paste(c(1:6), "Success"),"X", 1-0.172659, "Promising", c(1:6)))
names(exact_binom1) <- names(df1_long_1)

exact_binom1 <- exact_binom1 %>% mutate_at(c(2,5,7), as.numeric)
df1_long_1 <- rbind.data.frame(df1_long_1, exact_binom1)

# pdf("case1_scatter1.pdf", width = 7, height = 5)
df1_long_1 %>% ggplot(aes(x = n_success, y = power, group = interaction(is_success, label))) +
  # geom_line(aes(linetype = label, color = scenario)) + 
  geom_point(aes(color = label, shape = is_success), size = 3,
             position = position_dodge(width = 0.5)) + theme_bw() +
  guides(color = guide_legend(override.aes = list(size=2))) +
  # theme(axis.title.x = element_text(margin = margin(b = -5))) +
  scale_y_continuous(breaks = seq(0, 1, 0.1)) +
  scale_color_manual(values = c("MEM-Local" = "Red", "MEM-Global" = "blue", "Exact-Binomial" = "black")) +
  # scale_shape_manual(values = c("MEM-Local" = "o", "MEM-Global" = "x"))+
  scale_shape_manual(values = c("Non-Promising" = "o", "Promising" = "+"))+
  # scale_color_brewer(palette = "Set2")+
  labs(x = "\nNumber of Promising Baskets", y = "Basket-wise Power / Type I Error\n", 
       shape = "Basket Type", color = "Method")
# ggsave("./figure_for_submission/case1_scatter_1019.eps", width=7, height=5)

# dev.off()
```


```{r}
simon2stg <- ph2simon(pu=0.15, pa=0.45, ep1 = 0.017, ep2 = 0.2)
simon2stg
```


```{r}
r1 <- 1
n1 <- 6
n2 <- 19
r <- 7

p_rej0 <- sapply(c(0.15, 0.35, 0.45), function(p) {
  1-(pbinom(r1, n1, p) + sum(sapply(c((r1+1):min(n1, r)), function(x) 
  {dbinom(x, n1, p) * pbinom(r-x, n2, p)})))
})

p_rej0

fwer_simon <- 1 - (1-p_rej0[1])^6
fwer_simon
```

### Comparison with Simon's 2-stage design

```{r}
load("./data/case3_results.RData")

simon_results <- pmat[-8, ]
simon_results[pmat[-8, ] > 0.15] <- p_rej0[3]
simon_results[pmat[-8, ] <= 0.15] <- p_rej0[1]

df3 <- data.frame(rbind(tab3[, c(-1, -2, -9)], simon_results))
names(df3)[1:6] <- LETTERS[1:6]
df3$label <- c(rep("MEM-Local", 8), rep("Simon-2-Stage", 7))
df3$label <- factor(df3$label, levels = c("MEM-Local", "Simon-2-Stage"))
df3$sample_size <- rep(19, nrow(df3))
df3$scenario <- c(rep(c(paste(0:6, "Success"), "HHLMMH"), 2))[-16]


df3_long_1 <- tidyr::pivot_longer(df3, cols = c(1:6),
                                  names_to = "basket", values_to = "power")
df3_long_1$is_success <- rep(as.numeric(as.vector(t((pmat > 0.15)))), 2)[-c(91:96)]
df3_long_1$is_success <- factor(df3_long_1$is_success, 
                                labels = c("Non-Promising", "Promising"))
df3_long_1 <- df3_long_1 %>% filter(scenario != "HHLMMH")
df3_long_1$n_success <- substr(df3_long_1$scenario, 1, 1)

# pdf("case3_scatter.pdf", width = 7, height = 5)
df3_long_1 %>% ggplot(aes(x = n_success, y = power, group = interaction(is_success, label))) +
  # geom_line(aes(linetype = label, color = scenario)) + 
  geom_point(aes(color = label, shape = is_success), size = 3,
             position = position_dodge(width = 0.5)) + theme_bw() +
  guides(color = guide_legend(override.aes = list(size=2))) +
  scale_y_continuous(breaks = seq(0, 1, 0.1)) +
  scale_color_manual(values = c("MEM-Local" = "red", "Simon-2-Stage" = "blue")) +
  # scale_shape_manual(values = c("MEM-Local" = "o", "MEM-Global" = "x"))+
  scale_shape_manual(values = c("Non-Promising" = "o", "Promising" = "+"))+
  # scale_color_brewer(palette = "Set2")+
  labs(x = "\nNumber of Promising Baskets", y = "Basket-wise Power / Type I Error\n", 
       shape = "Basket Type", color = "Method")

ggsave("case3_scatter.eps", width=7, height=5)
```

#### Expected Sample Size

```{r}
simon_en_mat <- n1 + (1 - pbinom(r1, n1, pmat)) * n2

simon_en_mat

df4 <- rbind.data.frame(EN_sep, simon_en_mat)
names(df4)[1:6] <- LETTERS[1:6]
df4$label <- c(rep("MEM-Local", 8), rep("Simon-2-Stage", 8))
df4$label <- factor(df4$label, levels = c("MEM-Local", "Simon-2-Stage"))
# df4$sample_size <- rep(19, nrow(df4))
df4$scenario <- c(rep(c(paste(0:6, "Success"), "HHLMMH"), 2))


df4_long_1 <- tidyr::pivot_longer(df4, cols = c(1:6),
                                  names_to = "basket", values_to = "EN")
df4_long_1$is_success <- rep(as.numeric(as.vector(t((pmat > 0.15)))), 2)
df4_long_1$is_success <- factor(df4_long_1$is_success, 
                                labels = c("Non-Promising", "Promising"))
df4_long_1 <- df4_long_1 %>% filter(scenario != "HHLMMH")
df4_long_1$n_success <- substr(df4_long_1$scenario, 1, 1)

# pdf("EN_scatter1.pdf", width = 7, height = 5)
df4_long_1 %>% ggplot(aes(x = n_success, y = EN, group = interaction(is_success, label))) +
  # geom_line(aes(linetype = label, color = scenario)) + 
  geom_point(aes(color = label, shape = is_success), size = 3, 
             position = position_dodge(width = 0.5)) + theme_bw() +
  guides(color = guide_legend(override.aes = list(size=2))) +
  scale_y_continuous(breaks = seq(1, 25, 2), limits = c(1, 25)) +
  scale_color_manual(values = c("MEM-Local" = "red", "Simon-2-Stage" = "blue")) +
  # scale_shape_manual(values = c("MEM-Local" = "o", "MEM-Global" = "x"))+
  scale_shape_manual(values = c("Non-Promising" = "o", "Promising" = "+"))+
  # scale_color_brewer(palette = "Set2")+
  labs(x = "\nNumber of Promising Baskets", y = "Expected Sample Size\n", 
       shape = "Basket Type", color = "Method")

ggsave("figure_for_submission/EN_scatter1_1024.eps", width=7, height=5)
# dev.off()
```


```{r}
fwer_calc <- function(pp_list, p_vec, qf, p0=0.15, nsims=5000) {
  fut_arm <- p_vec <= p0
  fwer <- sum(sapply(pp_list, function(pp_l) 
    {any((pp_l > qf)[fut_arm])})) / 5000
  return(fwer)
}

fwer_local <- sapply(sim1_all, function(l) {
  fwer_calc(l$pp_all, l$pvec, 1-delta1)
})
fwer_local
```

```{r}
tab1 <- cbind(tab1[, -ncol(tab1)], fwer_local)
```


```{r}
load("./mem/eq_all_pp.RData")
Nmax <- rep(19, 6)
qf = 0.955  # B.Hobbs & R.Landin, 2018
single_stg_anal <- function(pvec, pp, qf_grid, p0=0.15, 
                            alpha=0.1, tuning=FALSE) {
  truth <- as.numeric(pvec > p0)
  n_basket <- ncol(pp)
  nsims <- nrow(pp)
  pars <- NULL
  for (qf in qf_grid) {
    is_futile <- apply(pp, 1, function(pp_i) {as.numeric(pp_i < qf)})
    rej_h0 <- rowSums(1 - is_futile) / nsims  # typeI error(H0) / marginal power(H1)
    fwer <- NA
    if (all(truth == 0)) {
      # fwer <- sum(sapply(1:ncol(is_futile), function(i) {
      #   any(is_futile[, i] == 0)
      # })) / nsims
      fwer <- sum(apply(is_futile, 2, function(is_fut) {any(is_fut==0)})) / nsims
      if (tuning) {
        if (fwer < alpha) {
          pars <- rbind(pars, c(qf, rej_h0, fwer))
        }
      }
      else {
        pars <- rbind(pars, c(qf, rej_h0, fwer))
      }
    }
    else {
      power2 <- sum(apply(is_futile, 2, function(record) {
        truth_map = as.logical(truth)
        all(record[truth_map] == 0) & all(record[!truth_map] != 0)
      })) / nsims
      pars <- rbind(pars, c(qf, rej_h0, power2))
    }
  }  # end for-loop
  colnames(pars) <- c("qf", paste0("power", LETTERS[1:n_basket]), "fwer_or_power")
  return(pars)
}

# tune_eq <-single_stg_anal(pmat[1, ], eq_all.pp[[1]], 
#                           qf_grid = seq(0.9, 1, 0.01), tuning = TRUE)
eq_results <-
  t(sapply(1:nrow(pmat), function(i)
       {single_stg_anal(pmat[i, ], eq_all.pp[[i]], qf_grid = qf)}))
# }

colnames(eq_results) <- c("qf", LETTERS[1:6], "fam_power")

# save(tab1, eq_results, file="./data/case1_results.RData")
eq_results
```

```{r}
fwer_calc <- function(pp_list, p_vec, qf, p0=0.15, nsims=5000) {
  fut_arm <- p_vec <= p0
  fwer <- sum(sapply(pp_list, function(pp_l) 
    {any((pp_l > qf)[fut_arm])})) / 5000
  return(fwer)
}

eq_fwer <- sapply(1:length(eq_all.pp), function(i) {
  pvec = pmat[i, ]
  sum(sapply(1:nrow(eq_all.pp[[i]]), function(r) {
    any((eq_all.pp[[i]][r, ] > qf)[pvec <= p0])
  })) / 5000
})
eq_fwer
```

```{r}
eq_results <- cbind(eq_results[, -8], eq_fwer)
```

### Case 3 Simulation Data

```{r}
load("./sim5000/sim3_main.RData")
qf_2stg <- c(0.776, 0.991)
fwer_calc_2stg <- function(pp_list, p_vec, qf_2stg, p0=0.15, nsims=5000) {
  fut_arm <- p_vec <= p0
  
  fwer <- sum(sapply(pp_list, function(pp_l) {
    # is_eff <- rep(FALSE, length(p_vec))
    is_fut <- rep(FALSE, length(p_vec))
    for (i in 1:2) {
      is_fut[pp_l[, i] < qf_2stg[i]] <- T
    }
    return(any((!is_fut)[fut_arm]))
    })) / 5000
  return(fwer)
}

case3_fwer_all <-sapply(1:8, function(i) {
  fwer_calc_2stg(sim3_main[[i]]$pp_all, sim3_main[[i]]$p0, qf_2stg)
})
# fwer_calc_2stg(sim3_main[[1]]$pp_all, sim3_main[[1]]$p0, qf_2stg)
case3_fwer_all
```

```{r}
tab3 <- cbind(tab3[, c(-1, -2, -9)], case3_fwer_all)
colnames(tab3) <- c(LETTERS[1:6], "FWER")
tab3
```


### Visualize posterior probabilities by local & global MEM

```{r}
df_all <- data.frame()
titles <- c(paste(c(0:6), "Success"), "HHLMMH")

for (i in 1:8) {
  local_pp <- t(sapply(1:5000, function(j) {sim1_all[[i]]$pp_all[[j]]}))
  colnames(local_pp) <- LETTERS[1:6]
  local_pp_long <- data.frame(local_pp) %>%
    pivot_longer(cols = c(1:6), names_to="Basket", values_to="PP")
  local_pp_long$Model <- "MEM-Local"
  local_pp_long$Scenario <- titles[i]
  
  global_long <- data.frame(eq_all.pp[[i]]) %>%
    pivot_longer(cols=c(1:6), names_to="Basket", values_to="PP")
  global_long$Model <- "MEM-Global"
  global_long$Scenario <- titles[i]
  df_all <- rbind(df_all, local_pp_long, global_long)
}

df_all$Model <- factor(df_all$Model, levels = c("MEM-Local", "MEM-Global"))

plt_all <- df_all %>% ggplot(aes(x=Basket, y=PP, color=Model,
                      group=interaction(Basket, Model))) +
  geom_boxplot(outlier.shape = 1) + 
  facet_wrap(~Scenario, nrow=2, scales="free_x") + theme_bw() +
  labs(y = "Posterior Probability")

# ggsave("./figure_for_submission/pp_plots_all1.eps", plot= plt_all, 
#        width=12, height=6)
```



```{r}
titles <- c(paste(c(0:6), "Success"), "HHLMMH")

plt_list <-
  lapply(1:length(eq_all.pp), function(i) {
  local_pp <- t(sapply(1:5000, function(j) {sim1_all[[i]]$pp_all[[j]]}))
  colnames(local_pp) <- LETTERS[1:6]
  pvec <- pmat[i, ]
  font <- rep("plain", 6)
  font_color <- rep("grey50", 6)
  font[which(pvec > 0.15)] <- "bold"
  font_color[which(pvec > 0.15)] <- "black"
  local_pp_long <- data.frame(local_pp) %>%
    pivot_longer(cols = c(1:6), names_to="Basket", values_to="PP")
  local_pp_long$Model <- "MEM-Local"
  
  global_long <- data.frame(eq_all.pp[[i]]) %>%
    pivot_longer(cols=c(1:6), names_to="Basket", values_to="PP")
  global_long$Model <- "MEM-Global"
  df_combine <- rbind(local_pp_long, global_long)
  df_combine$Model <- factor(df_combine$Model, 
                             levels = c("MEM-Local", "MEM-Global"))
  
  plt <- df_combine %>% 
          ggplot(aes(x=Basket, y=PP, color=Model,
                     group=interaction(Basket, Model))) +
          geom_boxplot(outlier.shape = 1) + theme_bw() + 
          theme(plot.title = element_text(hjust = 0.5),
                axis.text.x = element_text(face = font, color = font_color),
                axis.title.x = element_blank(),
                axis.title.y = element_blank()) +
          labs(title = titles[i])
  return(plt)
})
legend <- get_legend(
  plt_list[[1]]
)
plt_list_noleg <- lapply(plt_list, function(l) 
  {l + theme(legend.position = "none")})

# plt_list_nolab <- lapply(plt_list, function(l) 
#   {l + theme(legend.position = "none",
#              axis.text.y = element_blank(),
#              axis.ticks.y = element_blank(),
#              axis.title.y = element_blank())})
p_all <- plot_grid(plotlist = plt_list_noleg, nrow=2)
# row1 <- c(list(plt_list[[1]] + theme(legend.position = "none")), 
#           lapply(2:4, function(i) {plt_list_nolab[[i]]}))
# plt_row1 <- plot_grid(plot_grid(plotlist = row1, nrow=1), 
#                       rel_widths = c(1, 0.8, 0.8, 0.8))
# row2 <- c(list(plt_list[[5]] + theme(legend.position = "none")),
#           lapply(6:8, function(i) {plt_list_nolab[[i]]}))
# plt_row2 <- plot_grid(plotlist = row2, nrow=1)
# p_all <- plot_grid(plt_row1, plt_row2, align = "v", axis="l", nrow = 2)
# p_row1 <- plot_grid(plotlist = )
# p_all <- plot_gri
y.grob <- textGrob("Posterior Probability", rot=90)
x.grob <- textGrob("Baskets")

p_all1 <- plot_grid(p_all, legend, rel_widths = c(1, 0.1))
p_all1
p_all1.1 <- grid.arrange(arrangeGrob(p_all1, left = y.grob, bottom = x.grob))

plt_list[[1]] + theme(axis.text.x = element_text(face = c(rep("plain", 5), "bold"), color = c(rep("grey50", 5), "black")))
  # scale_x_discrete(labels=c("B"=expression(bold(B)),
  #                            "D"=expression(bold(D)),
  #                           "E"=expression(bold(E)), "F"=expression(bold(F)),
  #                           parse=TRUE))
ggsave("./figure_for_submission/pp_plots_all0.eps", plot= p_all1.1,
       width=12, height=6)
```


```{r}
load("./sim5000/sim5b_main.RData")
n_basket_5b <- 5
p0_5b <- 0.1
p1_5b <- 0.3
int_p <- 1

pmat_5b <- t(sapply(0:5, function(i) 
  {c(rep(p1_5b, i), rep(p0_5b, n_basket_5b-i))}))

# Find stopping boundary under global null
case5b_1 <- tuning(sim5b_main[[1]]$pp_all, int_p = int_p, 
                   pvec = pmat_5b[1, ],
                   qf_all = matrix(seq(0.88, 0.9, 0.001), ncol=1), 
                   fwer_thres = 0.1, single_stg = T)

case5b_all <- lapply(1:nrow(pmat_5b), function(i) {
  tuning(sim5b_main[[i]]$pp_all, int_p = int_p, pvec = pmat_5b[i, ],
         qf_all = matrix(0.894, ncol=1), 
         fwer_thres = 0.1, single_stg = T)
})
length(case5b_all)
tab_5bkt <- t(sapply(case5b_all, function(l) {
  l$pars
}))
tab_5bkt
# case5b_1$qf
# case5b_1$pars
```

```{r}

fwer_local_5 <- sapply(1:length(sim5b_main), function(i) {
  fwer_calc(sim5b_main[[i]]$pp_all, pmat_5b[i, ], 0.894)
})
fwer_local_5
```

```{r}
tab_5bkt <- cbind(tab_5bkt[, c(-1, -2, -8)], fwer_local_5)
colnames(tab_5bkt) <- c(LETTERS[1:5], "FWER")
tab_5bkt
rownames(tab_5bkt) <- paste(c(0:5), "Success")
tab_5bkt

library(xtable)
print(xtable(tab_5bkt,
             digits=c(0, 3, 3, 3, 3, 3, 3)), 
      scalebox = 0.9,
      include.colnames=TRUE,
      include.rownames=TRUE)

```

